// lib/models/car_model.dart

import 'package:hive/hive.dart';

// This part 'car_model.g.dart' will be generated by the build runner
part 'car_model.g.dart';

@HiveType(typeId: 0) // typeId must be unique for each model
class Car extends HiveObject {
  @HiveField(0)
  late String plateNumber;

  @HiveField(1)
  late String model;

  @HiveField(2)
  late String brand; // 'Make' from your UI

  @HiveField(3)
  late double currentMileage; // 'Odometer' from your UI

  @HiveField(4)
  String? tireSize;

  @HiveField(5)
  String? engine;

  @HiveField(6)
  String? lastService;

  // Constructor
  Car({
    required this.plateNumber,
    required this.model,
    required this.brand,
    required this.currentMileage,
    this.tireSize,
    this.engine,
    this.lastService,
  });
}
